Task 1
JollyGolf/cocktails-init pull request #1
Opened 2018-06-22 20:38 UTC by JollyGolf

2018-06-22 22:24 UTC, ShepelievD requested changes

2018-06-22 22:24 UTC, ShepelievD commented on css/style.css
> +}
Enter

2018-06-22 22:24 UTC, ShepelievD commented on src/index.js
> +      title_field.appendChild(title_text)
use camelCase

2018-06-22 22:24 UTC, ShepelievD commented on src/index.js
> +        if (array_ingridients[i] == '' || array_ingridients[i] == null || array_ingridients[i] == undefined) break
Wtf?

2018-06-22 22:24 UTC, ShepelievD commented on src/index.js
> +  const ingridient1 = document.getElementById('ingridient1')
What is the purpose?

2018-06-22 22:24 UTC, ShepelievD commented on src/index.js
> +      for (let i = 0; i < 15; i++) {
Foreach

2018-06-22 22:24 UTC, ShepelievD commented on src/index.js
> +        root.appendChild(hr)
Create wrapper for each element

2018-06-23 06:23 UTC, JollyGolf commented on src/index.js
> +        if (array_ingridients[i] == '' || array_ingridients[i] == null || array_ingridients[i] == undefined) break
Что тут?

2018-06-23 06:24 UTC, JollyGolf commented on src/index.js
> +      for (let i = 0; i < 15; i++) {
Изменить цикл на Foreach?

2018-06-23 06:32 UTC, JollyGolf commented on src/index.js
> +        root.appendChild(hr)
Для каждого ингредиента или для каждого коктейля?

2018-06-23 07:42 UTC, ShepelievD requested changes

2018-06-23 07:42 UTC, ShepelievD commented on src/index.js
> +      const instrunction_text = document.createTextNode('Instruction: '+ strInstructions)
camelCase

2018-06-23 07:42 UTC, ShepelievD commented on src/index.js
> +        return value != '' && value != null && value != undefined
!!value

2018-06-23 07:42 UTC, ShepelievD commented on src/index.js
> +      currentCocktail = currentCocktail+1;
смотри аргументы forEach

2018-06-23 07:42 UTC, ShepelievD commented on src/index.js
> +      ingridientsField.setAttribute('id', 'ingridients-'+currentCocktail)
почему id, зачем?

2018-06-23 07:42 UTC, ShepelievD commented on src/index.js
> +      ingridientsField.setAttribute('class', 'all_ingridients')
camelCase, для css используй BEM

2018-06-23 07:45 UTC, JollyGolf commented on src/index.js
> +        return value != '' && value != null && value != undefined
?

2018-06-25 08:07 UTC, ShepelievD requested changes

2018-06-25 08:07 UTC, ShepelievD commented on src/index.js
> +      function setAttributes(el, attrs) {
вынеси в utils.js

2018-06-25 08:07 UTC, ShepelievD commented on src/index.js
> +      setAttributes(cocktailField, { 'class': 'cocktail root__cocktail cocktail_item_'+index})
используй `${}`, class без ''

2018-06-25 08:07 UTC, ShepelievD commented on src/index.js
> +      titleField.appendChild(document.createTextNode('title: '+strDrink))
аналогично и тд

2018-06-25 08:07 UTC, ShepelievD commented on src/index.js
> +
втф, удали это всё

2018-06-25 08:07 UTC, ShepelievD commented on src/index.js
> +      let allIngridient = document.createTextNode(document.getElementsByClassName('ingridient_item_'+index)[0].textContent.slice(0, -2) + '.')
const

2018-06-25 08:07 UTC, ShepelievD commented on src/index.js
> +        for (let key2 of ingridients) {
кстати, мне кажется что правильно писать `ingredients`

```
ingridients.forEach((key) => rest[key] .... )
```

2018-06-25 14:34 UTC, ShepelievD requested changes

2018-06-25 14:34 UTC, ShepelievD commented on src/index.js
> +          }
выравнивание

2018-06-25 14:34 UTC, ShepelievD commented on src/index.js
> +      instructionField.appendChild(document.createTextNode('Instruction: '+ strInstructions))
пробелы вокруг +, смотри везде

2018-06-25 14:34 UTC, ShepelievD commented on src/index.js
> +      setAttributes(imageField, { 'src': strDrinkThumb, 'class': 'image cocktail__image'})
зачем кавычки возле 'src', 'class'?

2018-06-25 14:34 UTC, ShepelievD commented on src/index.js
> +      Object.keys(rest).filter((value) => value.match(/strIngredient\d+/)).forEach((key) => {
пиши красивенько

```
 Object.keys(rest)
    .filter((value) => value.match(/strIngredient\d+/))
    .forEach((key) => ........
```

2018-06-25 15:27 UTC, ShepelievD requested changes
подключи и настрой себе eslint

https://github.com/eslint/eslint
https://github.com/eslint/eslint/tree/master/packages/eslint-config-eslint

2018-06-28 14:33 UTC, ShepelievD approved these changes

2018-06-28 14:33 UTC, merged